### PR TITLE
Dialog_ColorPicker color fields fixes

### PR DESCRIPTION
**Pull request by Taranchuk**
Fixes issues with color fields not working basically

### CODE REVIEW

**Comment by ISOR3X** [comment]
Hex input and hue/sat work great now, only the hex field no longer updates when the color is changed through the other inputs.

**Comment by Taranchuk** [comment]
I've looked into it, but I couldn't figure out how to tell if the player is no longer focused on the hex field so I can just refresh the buffer string with the color value. At this moment I've spent like 2 hours on it and figured out that there are more important bugs to fix.

**Comment by ISOR3X** [comment]
Have you looked at how I did this for the age input?

**Comment by Taranchuk** [comment]
I didn't look, but I can check

**Pull request merged**
